version: '3'

services:
  django:
    build: /home/rewen/vladimirPay
    container_name: django
    command: bash -c "python3 backend/manage.py migrate && python3 backend/manage.py runserver 0.0.0.0:8000"
    volumes:
      - django-backend:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - pgdb
    environment:
      DEBUG: 'true'
      PYTHONPATH: /usr/src/app

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata: null
  django-backend: null