# Generated by Django 4.2.7 on 2023-12-01 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products_count',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.products')),
                ('available_quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products_price',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.products')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='available_quantity',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
    ]
