# Generated by Django 4.2.7 on 2023-11-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='transaction_id',
        ),
    ]
