# Generated by Django 4.2.7 on 2023-12-01 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
        ('transactions', '0002_remove_transactions_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.users'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD')], default='RUB', max_length=3),
        ),
    ]
