# Generated by Django 4.2.4 on 2023-12-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transactions_customer_alter_transactions_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='product_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='product_quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
