# Generated by Django 4.2.4 on 2023-12-08 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_count_products_price_and_more'),
        ('transactions', '0005_remove_transactions_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_transactions', to='products.products'),
        ),
    ]
