# Generated by Django 4.2.4 on 2023-12-08 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_count_products_price_and_more'),
        ('users', '0005_alter_log_action_description'),
        ('transactions', '0006_transactions_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Сумма', max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD')], default='RUB', help_text='Валюта', max_length=3),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Пользователь', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.users'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='product',
            field=models.ForeignKey(help_text='Товар', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_transactions', to='products.products'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='product_quantity',
            field=models.IntegerField(blank=True, default=1, help_text='Количество покупаемого продукта', null=True),
        ),
        migrations.CreateModel(
            name='Reasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(help_text='Причина отклонения', max_length=255)),
                ('transact', models.ForeignKey(help_text='Транзакция', on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.transactions')),
            ],
        ),
    ]
