# Generated by Django 4.2.4 on 2023-12-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_transactions_reason_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasons',
            name='description',
            field=models.CharField(blank=True, help_text='Причина отклонения', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reasons',
            name='reason',
            field=models.CharField(choices=[('M', 'Недостаточно средств'), ('C', 'Отменено пользователем'), ('Q', 'Недостаточное количество')], default='M', help_text='Причина отклонения'),
        ),
    ]
