# Generated by Django 4.2.7 on 2023-11-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(auto_created=True, default=0, unique=True, verbose_name='ID пользователя в системе')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_currency', models.CharField(max_length=3)),
            ],
        ),
    ]
