# Generated by Django 4.2.7 on 2023-12-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='Время действия')),
                ('action_description', models.TextField(blank=True, choices=[(0, 'Использование бота'), (1, 'Успешная регистрация пользователя'), (2, 'Неудачная попытка регистрации пользователя')], verbose_name='Описание действия')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD')], max_length=3)),
            ],
            options={
                'verbose_name': 'Пользователь',
            },
        ),
    ]
