# Generated by Django 4.2.4 on 2023-12-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_log_customer_log_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action_description',
            field=models.TextField(blank=True, choices=[(0, 'Успешная регистрация пользователя'), (1, 'Неудачная попытка регистрации пользователя')], verbose_name='Описание действия'),
        ),
    ]
